version: '3'
services: 
    ms-sql-server:
        # container_name: CarRentSQLServer
        image: mcr.microsoft.com/mssql/server:2019-latest
        env_file: 
            - Cridentials.env
        environment: 
            ACCEPT_EULA: "Y"
        ports:
            - "5001:1433"
    car-rent-api:
        build: .
        ports: 
            - "8080:80"
            - "8081:443"
        environment: 
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8081"
            ASPNETCORE_ENVIRONMENT: "Development"
        volumes: 
            - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
            - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
        depends_on: 
            - ms-sql-server
